# Site settings
title:       Parham Doustdar's Blog
email:       me@parhamdoustdar.com
author:      Parham Doustdar
description: "The Life of a Completely Blind Programmer in the Netherlands"
baseurl:     ""
url:         "https://www.parhamdoustdar.com"
encoding: UTF-8

# Google analytics
google_analytics: UA-75640034-1

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: parhamdoustdar

# Social icons
github_username: parhamdoustdar
bitbucket_username:
stackoverflow_id:
twitter_username: pd90
facebook_username: parham90
google_plus_id:
linkedin_username: parhamdoustdar
angellist_username:
medium_id: "@parhamdoustdar"
bitcoin_url:
paypal_url: http://paypal.me/pdoustdar
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     5
sass:
  compressed: true
plugins:
  - jekyll-sitemap
  - jekyll-paginate
